### ISSUE TITLE
Hi there,

### ISSUE THREAD

**Issue by dextronomous** [kanhavishva/keyhunt-ocl#1]
Is it that the program shows random addresses, wich i am not looking for,
while the -k option is also set and -u 1 the addresses it is showing me aren't inside my files. 
thanks for the help.

**Comment by kanhavishva** [comment]
It should not show any random address that isn't in the given file but still there are possibilities of the bugs.

I didn't encountered this type of issue yet.

First it checks in bloom filter, and then if result is positive then it checks in binary rmd160 hashes of the addresses and if it found, then it outputs.

**Comment by dextronomous** [comment]
ok thank you very much friend will do,
