### ISSUE TITLE
pls, help compilation

### ISSUE THREAD

**Issue by Noname400** [kanhavishva/keyhunt-ocl#11]
can't compile. tell me what to do?
![image](https://user-images.githubusercontent.com/74019756/127832752-cd01acde-b812-421a-b9ab-e6e0f5798300.png)

**Comment by Noname400** [comment]
or please add the hash change parameter after the required number of iterations. and everyone will already decide how often the hash needs to be changed for him. thank you so much for your work

**Comment by kanhavishva** [comment]
change debug to release

![image](https://user-images.githubusercontent.com/24961687/127838348-2112440a-70ff-4fd1-b73b-8bca424a72cf.png)

**Comment by Noname400** [comment]
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	C1047	Файл объекта или библиотеки "x64\Release\bloom.obj" был создан с более старой версией компилятора, чем другие объекты; выполните заново построение старых объектов и библиотек	keyhunt-ocl	D:\DownLoads\keyhunt-ocl-main\keyhunt-ocl\LINK	1

**Comment by Noname400** [comment]
![image](https://user-images.githubusercontent.com/74019756/127846151-f5bc9367-d9cb-4d72-87b9-259be9f29872.png)

**Comment by Noname400** [comment]
I figured it out. compilation was successful.
the question appeared:
how to compile with OPENCL 1.2?

DEVICE INFO:
        Device              : NVIDIA GeForce GTX 750
        Vendor              : NVIDIA Corporation (10de)
        Driver              : 471.41
        Profile             : FULL_PROFILE
        Version             : OpenCL 3.0 CUDA
        Max compute units   : 4
        Max workgroup size  : 1024
        Global memory       : 2147483648
        Max allocation      : 536870912

**Comment by Noname400** [comment]
It's work
